ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'READY_TO_SCHEDULE';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'CALL_SCHEDULED';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'IN_PROGRESS';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'NEXT_CALL_REQUIRED';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'OFFERED';
ALTER TYPE "LeadStatus" ADD VALUE IF NOT EXISTS 'REJECTED';

CREATE TYPE "LeadCallStatus" AS ENUM ('SCHEDULED', 'COMPLETED', 'PENDING_FEEDBACK', 'NO_SHOW', 'RESCHEDULED', 'CANCELLED');
CREATE TYPE "FeedbackCallStatus" AS ENUM ('TAKEN', 'RESCHEDULED', 'NO_SHOW', 'SHIFTED');
CREATE TYPE "FeedbackResult" AS ENUM ('PASSED', 'FAILED', 'NEED_NEXT_CALL', 'OFFERED', 'REJECTED', 'NO_DECISION');
