ALTER TYPE "JobStatus" RENAME TO "JobStatus_old";

CREATE TYPE "JobStatus" AS ENUM (
  'PENDING_APPROVAL',
  'APPROVED_BY_ADMIN',
  'REJECTED_BY_ADMIN',
  'NOT_APPLIED',
  'APPLIED',
  'REJECTED'
);

ALTER TABLE "Job" ALTER COLUMN "status" DROP DEFAULT;

ALTER TABLE "Job"
ALTER COLUMN "status" TYPE "JobStatus"
USING (
  CASE "status"::text
    WHEN 'NOT_APPLIED' THEN 'PENDING_APPROVAL'
    WHEN 'APPLIED' THEN 'APPROVED_BY_ADMIN'
    WHEN 'REJECTED' THEN 'REJECTED_BY_ADMIN'
    ELSE "status"::text
  END
)::"JobStatus";

ALTER TABLE "Job" ALTER COLUMN "status" SET DEFAULT 'PENDING_APPROVAL';

DROP TYPE "JobStatus_old";
